In [14]:
# Imports
import pandas as pd
import os
import typing
from functools import partial
from pprint import pprint
from pypif import pif
from pypif.obj import *

In [15]:
# Load Data
# Filter to comp
# Parse Vector
# Upload to citrination

In [16]:
# make pifs
def df_to_pif(row: pd.Series, pifs: list) -> pd.Series:
    sys = ChemicalSystem()
    sys.names = row['formula']
    sys.chemical_formula = row['formula']
    sys.properties = Property(name='stable', scalars=row['stable'])
    '''
    for name, val in row.iteritems():
        sys.properties.append(Property(name=name, scalars=Scalar(value=val)))
    '''
    pifs.append(sys)
    return row

In [17]:
load_path = os.path.join('data','processed_data.csv')
save_path = os.path.join('data','pifs_data.json')

In [18]:
df = pd.read_csv(load_path)

In [25]:
df.drop_duplicates()

            formula  stable
0                Ne       1
1                Cs       1
2                 K       1
3                Ba       1
4                Sr       1
5                Br       1
6                Na       1
7                La       1
8                Pr       1
9                Ce       1
10               Te       1
11               Pm       1
12               Gd       1
13                Y       1
14               Tb       1
15               Dy       1
16               Lu       1
17               Tl       1
18               Sn       1
19               Sc       1
20               Mg       1
21               Li       1
22                U       1
23               Np       1
24               Ta       1
25               Nb       1
26               Mo       1
27               Pt       1
28               Re       1
29               Pd       1
...             ...     ...
25690  Ca10.0 B90.0       0
25691   I10.0 B90.0       0
25692  Br10.0 B90.0       0
25693  Bi10.0 B90.0       0
25694  Pr10.0 B90.0       0
25695  Nd10.0 B90.0       0
25696  Sm10.0 B90.0       0
25697  Th10.0 B90.0       0
25698  Dy10.0 B90.0       0
25699  Ho10.0 B90.0       0
25700  Lu10.0 B90.0       0
25701  Tl10.0 B90.0       0
25702  Sc10.0 B90.0       0
25703  Ge10.0 B90.0       0
25704  Cd10.0 B90.0       0
25705  Li10.0 B90.0       0
25706   U10.0 B90.0       0
25707  Ga10.0 B90.0       0
25708  Np10.0 B90.0       0
25709  Nb10.0 B90.0       0
25710  Ag10.0 B90.0       0
25711  Al10.0 B90.0       0
25712  Mo10.0 B90.0       0
25713  Pd10.0 B90.0       0
25714  Tc10.0 B90.0       0
25715  Cr10.0 B90.0       0
25716  Cu10.0 B90.0       0
25717  Fe10.0 B90.0       0
25718  Ni10.0 B90.0       0
25719   C10.0 B90.0       0

[23230 rows x 2 columns]

In [19]:
pifs = []

In [20]:
dtp = partial(df_to_pif, pifs=pifs)

In [21]:
pif_tdf = df.apply(dtp, axis=1)

In [10]:
with open(save_path,'w') as f:
    pif.dump(pifs, f, indent=2)